<link rel="shortcut icon" type="image/x-icon" href="easyservices-website/favicon.ico">
theme: jekyll-theme-cayman
description: >- # this means to ignore newlines until "baseurl:"
  Oficjalna Strona Internetowa Dla Easy Services!
